### PR TITLE
chore(CI): build a portable binary in CI for different CPU architectures

### LINKED ISSUE #1387: CI may be broken by illegal instruction
The `start_with_multi_nodes` test sometimes failed with the `Illegal instruction` error

```bash
$ fetch http://127.0.0.1:8004/ {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: '{"jsonrpc":"2.0", "method":"eth_blockNumber", "params": [], "id":42}'
}
FetchError: request to http://127.0.0.1:8001/ failed, reason: connect ECONNREFUSED 127.0.0.1:8001
    at ClientRequest.<anonymous> (file:///home/runner/.npm/_npx/721a1717bb84573e/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:[52](https://github.com/axonweb3/axon/actions/runs/6021605629/job/16334858946?pr=1382#step:4:53)6:35)
    at ClientRequest.emit (node:domain:489:12)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  erroredSysCall: 'connect'
}
/home/runner/work/_temp/003aec82-f[57](https://github.com/axonweb3/axon/actions/runs/6021605629/job/16334858946?pr=1382#step:4:58)4-4384-b2c1-fd29b13a094c.sh: line 29:  1741 Illegal instruction     (core dumped) target/debug/axon run --config devtools/chain/nodes/node_1.toml --chain-spec devtools/chain/specs/multi_nodes_short_epoch_len/chain-spec.toml > /home/runner/work/_temp/ubuntu-22.04/multi-axon-nodes/node_1.log
```

### PR DESCRIPTION
**Pull request by Flouse**
## What this PR does / why we need it?

This PR tries to:
- fix https://github.com/axonweb3/axon/issues/1387
- fix `Illegal instruction` issues recorded in https://github.com/axonweb3/axon/issues/1374

> PORTABLE=1: This flag is used to build a portable binary that can run on different machines with different CPU architectures. It disables the use of CPU-specific optimizations and generates code that is compatible with a wide range of CPUs

> USE_SSE=1: This flag enables the use of SSE instructions, which are a set of CPU instructions that can perform multiple operations on multiple data elements in parallel. SSE instructions can significantly improve performance for certain types of computations, such as multimedia processing

### What is the impact of this PR?

No Breaking Change

<details><summary>CI Settings</summary><br/>

### **CI Usage**

**Tip**: Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [x] Web3 Compatible Tests
- [x] OCT 1-5 And 12-15
- [x] OCT 6-10
- [x] OCT 11
- [x] OCT 16-19
- [x] v3 Core Tests

### **CI Description**

| CI Name                                   | Description                                                               |
| ----------------------------------------- | ------------------------------------------------------------------------- |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                                       |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3                        |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin                      |

</details>

### CODE REVIEW

**Review by blckngm — COMMENTED** [review]
Why should we use `-march=native`? I thought the change would be to make ckb-rocksdb use a more portable CPU feature set.

**Review by KaoImin — DISMISSED** [review]

**Comment by Flouse** [comment]
> Why should we use `-march=native`? I thought the change would be to make ckb-rocksdb use a more portable CPU feature set.

```
rustc -C target-cpu=help
Available CPUs for this target:
    native         - Select the CPU of the current host

**Comment by blckngm** [comment]
Using `-march=native` may cause the same issue that cached objects may use instructions that the current host doesn't support. We should change rocksdb to not use `-march=native`, not change rust to use `-march=native`.

**Review by blckngm — APPROVED** [review]

**Comment by blckngm** [comment]
Ckb-rocksdb uses `PORTABLE=1`, `USE_SSE=1` by default so this change isn't necessary. If there are runners that  don't support avx2, we should use the `portable` feature of ckb-rocksdb to disable avx2.

**Review by KaoImin — APPROVED** [review]

**Pull request merged**
