### PR TITLE
refactor(cli): initialize chain without any secret key

### PR DESCRIPTION
**Pull request by chaoticlonghair**
## What this PR does / why we need it?

This PR remove the `key` parameter from the `init` sub-command.

Since #1454, the secret is not required anymore.

### What is the impact of this PR?

No Breaking Change

<details><summary>CI Settings</summary><br/>

### **CI Usage**

**Tip**: Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [ ] Web3 Compatible Tests
- [ ] OCT 1-5 And 12-15
- [ ] OCT 6-10
- [ ] OCT 11
- [ ] OCT 16-19
- [ ] v3 Core Tests

### **CI Description**

| CI Name                                   | Description                                                               |
| ----------------------------------------- | ------------------------------------------------------------------------- |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                                       |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3                        |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin                      |

</details>

### CODE REVIEW

**Comment by chaoticlonghair** [comment]
:warning: The following CI checks could NOT be passed unless this PR merged.

- OCT 1-5 And 12-15
- OCT 6-10
- OCT 11
- OCT 16-19
- v3 Core Tests
- Web3 Compatible Tests

Because only the workflow scripts in default branch will be called.

**Review by Flouse — APPROVED** [review]

**Review by KaoImin — APPROVED** [review]

**Pull request merged**
