### PR TITLE
refactor: use constant values as default values

### PR DESCRIPTION
**Pull request by chaoticlonghair**
**What this PR does / why we need it**:

Before this PR, some values use constant values to set the default values, and some are not.

<details><summary>Click for example.</summary>

https://github.com/axonweb3/axon/blob/4ef2f5608633d8a60bfd50ab337b4965de3b714b/core/consensus/src/engine.rs#L71-L79

In fact, the above code is the same as

```rust
let txs_root = { 
    TrieMerkle::from_iter(txs.hashes.iter().enumerate()) 
        .root_hash() 
        .unwrap_or_else(|err| { 
            panic!("failed to calculate trie root hash for transactions since {err}") 
        })
}; 
```

The only difference is avoiding some computations, so that improve a little performance.

---

</details>

In this PR:
- Unify the value assignments of those roots.
- Add documentation how these constant value come.

**Which issue(s) this PR fixes**:

Fixes #

**Which docs this PR relation**:

Ref #1318

**Which toolchain this PR adaption**:

No Breaking Change

**Special notes for your reviewer**:

NIL

**CI Description**

| CI Name                                   | Description                                                     |
| ----------------------------------------- | --------------------------------------------------------------- |
| *Chaos CI*                                | Test the liveness and robustness of Axon under terrible network condition    |
| *Cargo Clippy*                            | Run `cargo clippy --all --all-targets --all-features`      |
| *Coverage Test*                           | Get the unit test coverage report                             |
| *E2E Test*                                | Run end-to-end test to check interfaces                         |
| *Code Format*                             | Run `cargo +nightly fmt --all -- --check` and `cargo sort -gwc`     |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                               |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3             |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin           |

**CI Usage**

> Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [ ] Chaos CI
- [x] Cargo Clippy
- [ ] Coverage Test
- [x] E2E Tests
- [x] Code Format
- [x] Unit Tests
- [x] Web3 Compatible Tests
- [ ] OCT 1-5 And 12-15
- [ ] OCT 6-10
- [ ] OCT 11
- [ ] OCT 16-19
- [ ] v3 Core Tests

### CODE REVIEW

**Review by blckngm — DISMISSED** [review]

**Review by KaoImin — DISMISSED** [review]

**Comment by KaoImin** [comment]
This PR should be refactor rather than perf.

**Review by KaoImin — DISMISSED** [review]

**Comment by chaoticlonghair** [comment]
@KaoImin There is no break changes.

**Comment by KaoImin** [comment]
@yangby-cryptape need to rebase

**Review by KaoImin — APPROVED** [review]

**Review by blckngm — APPROVED** [review]

**Pull request merged**
