### PR TITLE
fix: `Hex` serde deserialize

### PR DESCRIPTION
**Pull request by chaoticlonghair**
## What this PR does / why we need it?

This PR fixes:

```
running 1 test
test types::primitive::tests::test_hex_serde_deserialize ... FAILED

failures:

failures:
    types::primitive::tests::test_hex_serde_deserialize

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 41 filtered out; finished in 0.00s


--- STDERR:              axon-protocol types::primitive::tests::test_hex_serde_deserialize ---
thread 'types::primitive::tests::test_hex_serde_deserialize' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: Error { inner: TomlError { message: "invalid type: string \"0x1234\", expected a borrowed byte array", original: Some("\n            key = \"0x1234\"\n        "), keys: ["key"], span: Some(19..27) } } }', protocol/src/types/primitive.rs:546:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### What is the impact of this PR?

No Breaking Change

**PR relation**:
- Ref #

**Special notes for your reviewer**:

Before this PR, the `serde_json` already works well:
https://github.com/axonweb3/axon/blob/c944e248706de540cd8da31cb70f8dce3d8af9a7/protocol/src/types/primitive.rs#L564-L569
https://github.com/axonweb3/axon/blob/c944e248706de540cd8da31cb70f8dce3d8af9a7/protocol/src/types/primitive.rs#L298-L302
https://github.com/axonweb3/axon/blob/c944e248706de540cd8da31cb70f8dce3d8af9a7/protocol/src/types/primitive.rs#L373-L375

<details><summary>CI Settings</summary><br/>

### **CI Usage**

**Tip**: Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [x] E2E Tests
- [x] Web3 Compatible Tests
- [x] OCT 1-5 And 12-15
- [x] OCT 6-10
- [x] OCT 11
- [x] OCT 16-19
- [x] v3 Core Tests

### **CI Description**

| CI Name                                   | Description                                                               |
| ----------------------------------------- | ------------------------------------------------------------------------- |
| *Chaos CI*                                | Test the liveness and robustness of Axon under terrible network condition |
| *Cargo Clippy*                            | Run `cargo clippy --all --all-targets --all-features`                     |
| *Coverage Test*                           | Get the unit test coverage report                                         |
| *E2E Test*                                | Run end-to-end test to check interfaces                                   |
| *Code Format*                             | Run `cargo +nightly fmt --all -- --check` and `cargo sort -gwc`           |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                                       |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3                        |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin                      |

</details>

### CODE REVIEW

**Comment by chaoticlonghair** [comment]
> The title of this PR does not conform the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). Please fix it, thx.

:sos: If anyone know how to pass this check, please fix the PR title, thx.

p.s. Even the CI looks like it is passed, but in the logs of that CI check, you could find that the check is failed.

**Review by Flouse — APPROVED** [review]

**Comment by blckngm** [comment]
Is this a bug in faster-hex? (It should first de-serialize to `String` or maybe `Cow<str>`, not `&[u8]`.)

**Comment by chaoticlonghair** [comment]
> Is this a bug in faster-hex? (It should first de-serialize to `String` or maybe `Cow<str>`, not `&[u8]`.)

I checked the following code:

```rust
#[serde(transparent)]                                                                                                    
pub struct Hex(#[serde(with = "faster_hex")] Bytes); 
```

And, it failed, too.

Ref: 
- [`faster-hex` official example](https://github.com/nervosnetwork/faster-hex/blob/635076e795b7a546942b89d736457c93e911770f/src/serde.rs#L159-L163).
  `faster-hex` use `serde_json` for unit tests, too.


I guess:
- `serde_json` knows every input fields are strings, it parses every fields from string, no matter with quotes or not.
- But `serde` doesn't, it deserialize all basic types directly (eg, `u8`, `bool`), no intermediate type (here, it's `string`).
  - So, you have to tell `serde`, parse it to a string, before pass to your customized parser.

**Comment by blckngm** [comment]
I guess it's because serde_json supports deserializing borrowed str/[u8], but toml doesn't.

It may fail with serde_json too if there are escapes in the json string.

**Review by blckngm — APPROVED** [review]

**Review by KaoImin — APPROVED** [review]

**Pull request merged**
