### PR TITLE
chore: bump Axon version to 0.3.0-alpha

### LINKED ISSUE #1596: Release Axon v0.3.0-beta
## Breaking changes since [Axon v0.2.0-beta.2](https://github.com/axonweb3/axon/releases/tag/v0.2.0-beta.2)
- [x] https://github.com/axonweb3/axon/pull/1580 @driftluo 
- [x] https://github.com/axonweb3/axon/pull/1591 @KaoImin 
- [x] https://github.com/axonweb3/axon/pull/1576 @wenyuanhust 
  related issue: https://github.com/axonweb3/axon/issues/1573
- [x] https://github.com/axonweb3/axon/pull/1597

## Optional PRs or issues
- https://github.com/axonweb3/axon/pull/1601
- [x] https://github.com/axonweb3/axon/issues/1586
  > @yangby-cryptape : If `MIN_TRANSACTION_GAS_LIMIT` was a consensus parameter, then the bugfix of this issue will be a break change.
- [x] https://github.com/axonweb3/axon/issues/1584 
  
## Test
- 0.3.0-alpha branch: https://github.com/axonweb3/axon/commits/0.3.0-alpha

### PR DESCRIPTION
**Pull request by Flouse**
## Changes
- [chore(docker): suffix date and sha to branch_tags](https://github.com/axonweb3/axon/commit/a290459961df602a79953edff227f0f377ac241c)
- [docs: update CHANGELOG.md](https://github.com/axonweb3/axon/commit/8315c5243a07dc02cbd86382483d4ec1fbf24f6f)
- [docs: add version explanation](https://github.com/axonweb3/axon/commit/57d55227ce90cd4ecef445075cdbe01f85ed9bb1)
- [chore: bump axon version to 0.3.0-dev](https://github.com/axonweb3/axon/commit/986943f57ee7e7ee11befdd9f63531b1f0535e44)

<details><summary>CI Settings</summary><br/>

### **CI Usage**

**Tip**: Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [x] Web3 Compatible Tests
- [x] OpenZeppelin tests
- [x] v3 Core Tests

### **CI Description**

| CI Name                | Description                                                                                             |
| ---------------------- | ------------------------------------------------------------------------------------------------------- |
| *Web3 Compatible Test* | Test the Web3 compatibility of Axon                                                                     |
| *v3 Core Test*         | Run the compatibility tests provided by Uniswap V3                                                      |
| *OpenZeppelin tests*   | Run the compatibility tests provided by OpenZeppelin, including OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19 |
</details>

### CODE REVIEW

**Comment by KaoImin** [comment]
`dev` is not a preceding identifier, why use this?

**Comment by Flouse** [comment]
> `dev` is not a preceding identifier, why use this?

My plan is to test 0.3.0-dev interanl, and then bump to v0.3.0-beta later if everything goes well.

Do think `0.3.0-alpha` is better than 0.3.0-dev?

**Comment by KaoImin** [comment]
> > `dev` is not a preceding identifier, why use this?
> 
> My plan is to test 0.3.0-dev interanl, and then bump to v0.3.0-beta later if everything goes well.
> 
> Do think `0.3.0-alpha` is better than 0.3.0-dev?

If only want to do some internal tests, no need to release a version. A commit ID is enough or checkout a branch.

**Review by Simon-Tl — DISMISSED** [review]

**Comment by Flouse** [comment]
> If only want to do some internal tests, no need to release a version. A commit ID is enough or checkout a branch.

1. updated: [chore: bump Axon version to 0.3.0-alpha](https://github.com/axonweb3/axon/pull/1615/commits/a88faf8b8373e84c29464aa0eb71554069e6237a)
2. just want a more readable version name for `web3_clientVersion` RPC and `axon --version`
2. I won't create a new release/tag for 0.3.0-alpha
3. created a new branch [0.3.0-alpha](https://github.com/axonweb3/axon/commits/0.3.0-alpha) to trigger the docker image building workflow

**Review by KaoImin — APPROVED** [review]

**Pull request merged**
