### PR TITLE
refactor: remove first genesis transaction

### LINKED ISSUE #1305: Transactions root of genesis block is incorrect
## Current Behavior

When calculating the genesis hash as previous hash of block 1, the transactions root is not set.

I'm not sure whether there is any transactions in genesis block.

But, even there is no transactions, the transactions root still could NOT be zeros, since there is a default value `RLP_NULL`.

https://github.com/axonweb3/axon/blob/8f3eded7d2d3a4e844d45e37faf585a3739d81b0/core/consensus/src/engine.rs#L73-L79

https://github.com/axonweb3/axon/blob/8f3eded7d2d3a4e844d45e37faf585a3739d81b0/protocol/src/types/primitive.rs#L33-L36

### Expected Behavior

Transactions root in genesis block should follow the consensus rules.

As a comparison, the receipts root and state root are refreshed before saved.

https://github.com/axonweb3/axon/blob/8f3eded7d2d3a4e844d45e37faf585a3739d81b0/core/run/src/lib.rs#L168-L172

### OS

Not Associated

### Axon version

v0.1.0-beta.5

### Kernel

Not Associated

### Relevant log output

_No response_

### Anything else?

Sadly, if it has a fix, the fix will be a break change.

And, please check all of the following fields again:

https://github.com/axonweb3/axon/blob/8f3eded7d2d3a4e844d45e37faf585a3739d81b0/devtools/chain/genesis_single_node.json#L4-L29

Which fields should be reset after the genesis block executed?

Select them in the following list:

- [ ] version
- [ ] prev_hash
- [ ] proposer
- [x] state_root
- [x] transactions_root
- [x] signed_txs_hash
- [x] receipts_root
- [x] log_bloom
- [ ] difficulty
- [ ] timestamp
- [ ] number
- [x] gas_used
- [ ] gas_limit
- [ ] extra_data
- [ ] mixed_hash
- [ ] nonce
- [ ] base_fee_per_gas
- [ ] proof
- [ ] call_system_script_count
- [ ] chain_id

### LINKED ISSUE #1408: The genesis transactions are opaque with poor readability
### What happened

At present, the genesis transactions are generated from previous genesis transactions.

https://github.com/axonweb3/axon/blob/283195b357b60b5a023d7d0610396e4842da86ea/devtools/genesis-generator/src/main.rs#L42-L53

- So, what are the first genesis transactions?

  How to generate the first genesis transactions?

- Since the previous genesis transactions are binary data, how to prove they are safety and trusted, and there are no malicious behaviors in them.

Should the genesis transactions be generated from configurations?

### PR DESCRIPTION
**Pull request by chaoticlonghair**
## What this PR does / why we need it?

This PR remove the first genesis transaction.

The final goal is to remove the private key which is used to initialize a chain.

The owner of that private key is the admin of the contract in the first genesis transaction.
That makes the chain to be centralized.

<details><summary>CI Settings</summary><br/>

### **CI Usage**

**Tip**: Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [x] E2E Tests
- [x] Web3 Compatible Tests
- [x] OCT 1-5 And 12-15
- [x] OCT 6-10
- [x] OCT 11
- [x] OCT 16-19
- [x] v3 Core Tests

### **CI Description**

| CI Name                                   | Description                                                               |
| ----------------------------------------- | ------------------------------------------------------------------------- |
| *Chaos CI*                                | Test the liveness and robustness of Axon under terrible network condition |
| *Cargo Clippy*                            | Run `cargo clippy --all --all-targets --all-features`                     |
| *Coverage Test*                           | Get the unit test coverage report                                         |
| *E2E Test*                                | Run end-to-end test to check interfaces                                   |
| *Code Format*                             | Run `cargo +nightly fmt --all -- --check` and `cargo sort -gwc`           |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                                       |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3                        |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin                      |

</details>

### CODE REVIEW

**Review by Flouse — DISMISSED** [review]
Please update devtools/chain/README.md as well.

https://github.com/axonweb3/axon/blob/a3ecd5796fcf44bbd57253dd50a250668cfd405e/devtools/chain/README.md?plain=1#L1-L4

**Review by Flouse — APPROVED** [review]

**Review by KaoImin — APPROVED** [review]

**Pull request merged**
