### PR TITLE
refactor!: remove useless fields in `BlockHeader`

### LINKED ISSUE #1335: Total difficulty always be zero, but every block difficulty always be one.
### Current Behavior

Total difficulty always be zero, but every block difficulty always be one.

It doesn't make sense.

https://github.com/axonweb3/axon/blob/4cf06e55c39fe4349eb7ba82edbeb9e04787008b/protocol/src/types/block.rs#L151

https://github.com/axonweb3/axon/blob/4cf06e55c39fe4349eb7ba82edbeb9e04787008b/core/api/src/jsonrpc/web3_types.rs#L322

Same situation (just be constant) for `Header.nonce`:

https://github.com/axonweb3/axon/blob/4cf06e55c39fe4349eb7ba82edbeb9e04787008b/core/api/src/jsonrpc/web3_types.rs#L337
https://github.com/axonweb3/axon/blob/4cf06e55c39fe4349eb7ba82edbeb9e04787008b/core/api/src/jsonrpc/web3_types.rs#L847

### Expected Behavior

Proposals:

- Should Axon just remove `difficulty` field from `Header`?

  Then set `Web3Block.difficulty` to be constant `U256::zero()`.

- The `nonce` field in `Header` is useless, too.

  Should Axon just remove `nonce` field from `Header`?

  Then set `Web3Block.nonce` to be constant `U256::zero()`.

Break changes:
- Block (header) hashes.

### Anything else?

The fields `difficulty` and `nonce` in `Header` are used when calculates its hash.

If Axon want to remove them, they have to be removed before release a no-break-changes version.

Ref: https://github.com/axonweb3/axon/pull/1332#discussion_r1297929850

### PR DESCRIPTION
**Pull request by KaoImin**
## What this PR does / why we need it?

This PR remove these three fields in `Header`:
1. `difficulty`
2. `nonce`
3. `mixed_hash`

They are all mining related and useless to Axon. The rpc will return the default value.

### What is the impact of this PR?

⚠️This is a breaking change.

<details><summary>CI Settings</summary><br/>

### **CI Usage**

**Tip**: Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [x] Cargo Clippy
- [ ] Coverage Test
- [x] E2E Tests
- [x] Code Format
- [x] Unit Tests
- [x] Web3 Compatible Tests
- [x] OCT 1-5 And 12-15
- [x] OCT 6-10
- [x] OCT 11
- [x] OCT 16-19
- [x] v3 Core Tests

### **CI Description**

| CI Name                                   | Description                                                               |
| ----------------------------------------- | ------------------------------------------------------------------------- |
| *Chaos CI*                                | Test the liveness and robustness of Axon under terrible network condition |
| *Cargo Clippy*                            | Run `cargo clippy --all --all-targets --all-features`                     |
| *Coverage Test*                           | Get the unit test coverage report                                         |
| *E2E Test*                                | Run end-to-end test to check interfaces                                   |
| *Code Format*                             | Run `cargo +nightly fmt --all -- --check` and `cargo sort -gwc`           |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                                       |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3                        |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin                      |

</details>

### CODE REVIEW

**Review by driftluo — DISMISSED** [review]

**Review by chaoticlonghair — DISMISSED** [review]

**Review by driftluo — DISMISSED** [review]

**Review by chaoticlonghair — DISMISSED** [review]

**Review by driftluo — DISMISSED** [review]

**Review by Flouse — COMMENTED** [review]
Is it necessary to update the test data?
https://github.com/axonweb3/axon/blob/db0c6083339a44e46962bd113c3c5798a740ddc4/tests/data/genesis.json#L12-L19

**Review by Flouse — APPROVED** [review]

**Review by driftluo — APPROVED** [review]

**Review by chaoticlonghair — APPROVED** [review]

**Pull request merged**
