### PR TITLE
ci: fix the check logic for Axon node status

### PR DESCRIPTION
**Pull request by sunchengzhu**
## What this PR does / why we need it?

This PR is used to fix the problem of https://github.com/axonweb3/axon/pull/1445

### What is the impact of this PR?

No Breaking Change

<details><summary>CI Settings</summary><br/>

### **CI Usage**

**Tip**: Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [x] E2E Tests
- [x] Web3 Compatible Tests
- [x] OCT 1-5 And 12-15
- [x] OCT 6-10
- [x] OCT 11
- [x] OCT 16-19
- [x] v3 Core Tests

### **CI Description**

| CI Name                                   | Description                                                               |
| ----------------------------------------- | ------------------------------------------------------------------------- |
| *Chaos CI*                                | Test the liveness and robustness of Axon under terrible network condition |
| *Cargo Clippy*                            | Run `cargo clippy --all --all-targets --all-features`                     |
| *Coverage Test*                           | Get the unit test coverage report                                         |
| *E2E Test*                                | Run end-to-end test to check interfaces                                   |
| *Code Format*                             | Run `cargo +nightly fmt --all -- --check` and `cargo sort -gwc`           |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                                       |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3                        |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin                      |

</details>

### CODE REVIEW

**Comment by chaoticlonghair** [comment]
Today, `sleep 20`.

With more code added, `sleep 30` next week, `sleep 40` next month, ...

I think such unpredictable tests should NOT be CI checks.

**Comment by sunchengzhu** [comment]
> Today, `sleep 20`.
> 
> With more code added, `sleep 30` next week, `sleep 40` next month, ...
> 
> I think such unpredictable tests should NOT be CI checks.

@yangby-cryptape 
I sbmitted [a new commit](https://github.com/axonweb3/axon/commit/375000ba980228dabe61bf0a626bfb04438fcc97) to solve the problem you mentioned.

**Comment by Flouse** [comment]
I pushed the commit (refs/pull/1446/head = [375000b](https://github.com/axonweb3/axon/pull/1446/commits/375000ba980228dabe61bf0a626bfb04438fcc97)) to my forked repo to run [tests](https://github.com/flouse/axon/actions):
image

**Review by chaoticlonghair — DISMISSED** [review]

**Review by Flouse — CHANGES_REQUESTED** [review]
## Tests on Axon commit a3ba757 failed
image

**Review by Flouse — APPROVED** [review]

**Pull request merged**
